/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.InstrumentoDAO;
import controller.JDBCUtil;
import javax.swing.table.DefaultTableModel;
import model.Instrumento;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Cris
 */
public class JanelaInstrumentosSQL extends javax.swing.JFrame {
    
    InstrumentoDAO dao = new InstrumentoDAO();
    private Instrumento instrumento = new Instrumento();
    
    /**
     * Creates new form JanelaCliente
     */
    public JanelaInstrumentosSQL() {
        this.setTitle("Instrumentos");
        initComponents();
        
        dao.CriaConexao();
    }
    
    public void listarTab(){
        DefaultTableModel modelo = (DefaultTableModel) tblInst.getModel();
        
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        try{
            dao.ConsultarTodos();
            dao.getRsdados();
            
            while(dao.getRsdados().next()){
                instrumento = dao.getInstrumento();
                modelo.insertRow(posLin, new Object[]{instrumento.getId(), instrumento.getNome(), instrumento.getDescricao(), instrumento.getPreco()});
                posLin++;
            }
        } catch (SQLException erro) {
            System.out.println("Falha na conexao, comando sql = " + erro);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIdade = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonLer = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInst = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        Busca = new javax.swing.JButton();
        Deleta = new javax.swing.JButton();
        Edita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 550));

        jLabel1.setText("Produto:");

        jLabel2.setText("Preço:");

        jLabel3.setText("Cliente:");

        jButtonLer.setText("Ler");
        jButtonLer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLerMouseClicked(evt);
            }
        });
        jButtonLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLerActionPerformed(evt);
            }
        });

        jButtonGravar.setText("Gravar");
        jButtonGravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGravarMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel4.setText("COMPRAS");

        tblInst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "PRODUTO", "CLIENTE", "PREÇO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInst);
        if (tblInst.getColumnModel().getColumnCount() > 0) {
            tblInst.getColumnModel().getColumn(0).setResizable(false);
            tblInst.getColumnModel().getColumn(1).setResizable(false);
            tblInst.getColumnModel().getColumn(2).setResizable(false);
            tblInst.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel5.setText("OPERAÇÕES COM ID:");

        Busca.setText("Buscar");
        Busca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscaMouseClicked(evt);
            }
        });

        Deleta.setText("Deletar");
        Deleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletaMouseClicked(evt);
            }
        });

        Edita.setText("Editar");
        Edita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNome)
                                    .addComponent(jTextFieldEmail)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 357, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonLer, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                                .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Busca, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Deleta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Edita, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(231, 231, 231))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLer)
                    .addComponent(jButtonGravar))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Busca)
                    .addComponent(Deleta)
                    .addComponent(Edita))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(564, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGravarMouseClicked
        int id = 0;
        
        try{
            dao.ConsultarTodos();
            dao.getRsdados();
            
            while(dao.getRsdados().next()){
                id++;
            }
        } catch (SQLException erro) {
            System.out.println("Falha na conexao, comando sql = " + erro);
        } 
        
        instrumento.setId(id);
        instrumento.setNome(jTextFieldNome.getText());
        instrumento.setPreco(Double.valueOf(jTextFieldIdade.getText()));
        instrumento.setDescricao(jTextFieldEmail.getText());
        
        Instrumento cli = instrumento;
        if (dao.Inserir(cli)) {
            JOptionPane.showMessageDialog(this, "Compra inserida com sucesso.");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao inserir compra.");
        }
    }//GEN-LAST:event_jButtonGravarMouseClicked

    private void jButtonLerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLerMouseClicked
        listarTab(); 
    }//GEN-LAST:event_jButtonLerMouseClicked

    private void jButtonLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLerActionPerformed

    private void DeletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletaMouseClicked
        int id = Integer.parseInt(jTextFieldId.getText());
        
        Instrumento deleted = new Instrumento();
        
        try{
            dao.ConsultarTodos();
            dao.getRsdados();
            
            while(dao.getRsdados().next()){
                instrumento = dao.getInstrumento();
                if(instrumento.getId() == id){
                    if (dao.Excluir(instrumento)) {
                        JOptionPane.showMessageDialog(this, "Compra excluída com sucesso.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao excluir compra.");
                    }
                }
            }
        } catch (SQLException erro) {
            System.out.println("Falha na conexao, comando sql = " + erro);
        }  
        listarTab(); 
    }//GEN-LAST:event_DeletaMouseClicked

    private void BuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscaMouseClicked
        int id = Integer.parseInt(jTextFieldId.getText());
        
        try{
            dao.ConsultarTodos();
            dao.getRsdados();
            
            while(dao.getRsdados().next()){
                instrumento = dao.getInstrumento();
                if(instrumento.getId() == id){
                    DefaultTableModel modelo = (DefaultTableModel) tblInst.getModel();
        
                    int posLin = 0;
                    modelo.setRowCount(posLin);
                
                    modelo.insertRow(posLin, new Object[]{instrumento.getId(), instrumento.getNome(), instrumento.getDescricao(), instrumento.getPreco()});
                }
            }
        } catch (SQLException erro) {
            System.out.println("Falha na conexao, comando sql = " + erro);
        }  
    }//GEN-LAST:event_BuscaMouseClicked

    private void EditaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditaMouseClicked
        int id = Integer.parseInt(jTextFieldId.getText());
        instrumento.setId(id);
        instrumento.setNome(jTextFieldNome.getText());
        instrumento.setPreco(Double.valueOf(jTextFieldIdade.getText()));
        instrumento.setDescricao(jTextFieldEmail.getText());
        if (dao.Alterar(instrumento)) {
            JOptionPane.showMessageDialog(this, "Compra alterada com sucesso.");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar compra.");
        }
        listarTab(); 
    }//GEN-LAST:event_EditaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaInstrumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaInstrumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaInstrumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaInstrumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaInstrumentosSQL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Busca;
    private javax.swing.JButton Deleta;
    private javax.swing.JButton Edita;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonLer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTable tblInst;
    // End of variables declaration//GEN-END:variables
}
