/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import controle.ControleRelatorios;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 * @author Cris
 */
public class JanelaClienteRelatorioOO extends javax.swing.JFrame {

    ControleRelatorios controle = new ControleRelatorios();

    /**
     * Recupera o parâmetro do usuário para criar um objeto Map que será usado
     * no relatório.
     */
    private Map constroiParametrosCliente() {
        Map params = new HashMap();

        int max = Integer.valueOf(JOptionPane.showInputDialog(
                this,
                "Digite a idade máxima para o relatório",
                "Entrada de dados",
                JOptionPane.QUESTION_MESSAGE));

        params.put("idademax", max);
        //params.put("idcliente", 2);
        //params.put("nome", "zeh");
        return params;
    }

    private Map constroiParametrosProduto() {
        Map params = new HashMap();
        int codp = Integer.valueOf(
                JOptionPane.showInputDialog(
                        this,
                        "Digite o código do Produto",
                        "Entrada de dados",
                        JOptionPane.QUESTION_MESSAGE));
        params.put("idProduto", codp);
        return params;
    }

    /**
     * Creates new form JanelaCliente
     */
    public JanelaClienteRelatorioOO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemRelatorioClientes = new javax.swing.JMenuItem();
        jMenuItemSalvaRelatorioClientes = new javax.swing.JMenuItem();
        jMenuItemVisualizaRelatorioClientesporIdade = new javax.swing.JMenuItem();
        jMenuItemSalvaRelatorioClientesporIdade = new javax.swing.JMenuItem();
        jMenuItemRelatorioProdutos = new javax.swing.JMenuItem();
        jMenuItemRelatorioVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Aplicação");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatórios");

        jMenuItemRelatorioClientes.setText("Visualiza Relatório de Clientes");
        jMenuItemRelatorioClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioClientesActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRelatorioClientes);

        jMenuItemSalvaRelatorioClientes.setText("Salva Relatório de Clientes em arquivo");
        jMenuItemSalvaRelatorioClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalvaRelatorioClientesActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSalvaRelatorioClientes);

        jMenuItemVisualizaRelatorioClientesporIdade.setText("Visualiza Relatório de Clientes por idade");
        jMenuItemVisualizaRelatorioClientesporIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizaRelatorioClientesporIdadeActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemVisualizaRelatorioClientesporIdade);

        jMenuItemSalvaRelatorioClientesporIdade.setText("Salva Relatório de Clientes por idade em arquivo");
        jMenuItemSalvaRelatorioClientesporIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalvaRelatorioClientesporIdadeActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSalvaRelatorioClientesporIdade);

        jMenuItemRelatorioProdutos.setText("Relatório de Produtos");
        jMenuItemRelatorioProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioProdutosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRelatorioProdutos);

        jMenuItemRelatorioVendas.setText("Relatório de Vendas por Região");
        jMenuItemRelatorioVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioVendasActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRelatorioVendas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(591, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemRelatorioClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioClientesActionPerformed
        controle.RelatorioCliente(true);//visualiza relatorio clientes
    }//GEN-LAST:event_jMenuItemRelatorioClientesActionPerformed

    private void jMenuItemSalvaRelatorioClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalvaRelatorioClientesActionPerformed
        controle.RelatorioCliente(false);//visualiza relatorio clientes
    }//GEN-LAST:event_jMenuItemSalvaRelatorioClientesActionPerformed

    private void jMenuItemVisualizaRelatorioClientesporIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizaRelatorioClientesporIdadeActionPerformed
        controle.RelatorioClienteParametro(constroiParametrosCliente(), true);//relatorio cliente com parametro
    }//GEN-LAST:event_jMenuItemVisualizaRelatorioClientesporIdadeActionPerformed

    private void jMenuItemSalvaRelatorioClientesporIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalvaRelatorioClientesporIdadeActionPerformed
        controle.RelatorioClienteParametro(constroiParametrosCliente(), false);//salva arquivo pdf com relatorio de clientes
    }//GEN-LAST:event_jMenuItemSalvaRelatorioClientesporIdadeActionPerformed

    private void jMenuItemRelatorioProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioProdutosActionPerformed
        controle.RelatorioProdutos(constroiParametrosProduto());
    }//GEN-LAST:event_jMenuItemRelatorioProdutosActionPerformed

    private void jMenuItemRelatorioVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioVendasActionPerformed
        controle.RelatorioVendas();
    }//GEN-LAST:event_jMenuItemRelatorioVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaClienteRelatorioOO.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaClienteRelatorioOO.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaClienteRelatorioOO.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaClienteRelatorioOO.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaClienteRelatorioOO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemRelatorioClientes;
    private javax.swing.JMenuItem jMenuItemRelatorioProdutos;
    private javax.swing.JMenuItem jMenuItemRelatorioVendas;
    private javax.swing.JMenuItem jMenuItemSalvaRelatorioClientes;
    private javax.swing.JMenuItem jMenuItemSalvaRelatorioClientesporIdade;
    private javax.swing.JMenuItem jMenuItemVisualizaRelatorioClientesporIdade;
    // End of variables declaration//GEN-END:variables
}
